# Generated by Django 3.2.3 on 2021-05-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["quiz", "topic", "question"]},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["title"], "verbose_name_plural": "Quizes"},
        ),
    ]
