# Generated by Django 3.2.3 on 2021-05-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedreader", "0002_entry_media_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="always_load",
            field=models.BooleanField(default=False),
        ),
    ]
