# Generated by Django 2.0.6 on 2018-06-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.DateTimeField()),
                ("label", models.TextField()),
            ],
            options={"ordering": ["label"]},
        )
    ]
