# Generated by Django 2.0.5 on 2018-06-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("mpages", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mpages.Page",
                    ),
                ),
                (
                    "published",
                    models.DateField(
                        blank=True,
                        help_text="dd/mm/yyyy",
                        null=True,
                        verbose_name="Date Published",
                    ),
                ),
            ],
            bases=("mpages.page",),
        )
    ]
